# 12 — Model Training and Inference

## Introduction

A Machine Learning system has two important stages:

1. **Training**
2. **Inference**

During **training**, a Machine Learning algorithm learns patterns from training data.

During **inference**, the trained model receives input data and produces predictions.

The basic process is:

$$
\text{Training Data}
\rightarrow
\text{Learning Algorithm}
\rightarrow
\text{Trained Model}
$$

Then:

$$
\text{New Data}
\rightarrow
\text{Trained Model}
\rightarrow
\text{Prediction}
$$

This notebook introduces the practical process of training a Machine Learning model and using that trained model to make predictions.

## 1. What Is Model Training?

**Model training** is the process of learning a Machine Learning model from training data.

For supervised learning, the training data contains:

- Features
- Target values

The training dataset can be represented as:

$$
D_{\text{train}}
=
\{(x_i,y_i)\}_{i=1}^{m}
$$

where:

- $x_i$ represents the feature vector of the $i$-th sample.
- $y_i$ represents the corresponding target.
- $m$ represents the number of training samples.

The learning algorithm uses these examples to learn suitable model parameters.

Conceptually:

$$
(X_{\text{train}},y_{\text{train}})
\rightarrow
\text{Learning Algorithm}
\rightarrow
\text{Trained Model}
$$

The purpose of training is to learn a function that can produce useful predictions for new inputs.

## 2. A Simple Training Problem

We will use a simple regression problem.

Suppose we want to predict a student's exam score from the number of hours they studied.

The feature is:

$$
x=\text{Study Hours}
$$

The target is:

$$
y=\text{Exam Score}
$$

Example data:

| Study Hours | Exam Score |
|---:|---:|
| 1 | 35 |
| 2 | 42 |
| 3 | 50 |
| 4 | 58 |
| 5 | 65 |
| 6 | 72 |

The model will attempt to learn the relationship between study hours and exam score.

In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression

In [2]:
X = np.array([
    [1],
    [2],
    [3],
    [4],
    [5],
    [6]
])

y = np.array([
    35,
    42,
    50,
    58,
    65,
    72
])

print("Features:")
print(X)

print("\nTarget:")
print(y)

Features:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Target:
[35 42 50 58 65 72]


## 3. Features and Target

In scikit-learn, input features are normally represented as a two-dimensional structure.

If there are $m$ samples and $n$ features:

$$
X\in\mathbb{R}^{m\times n}
$$

The target is represented separately:

$$
y\in\mathbb{R}^{m}
$$

For our example:

$$
m=6
$$

and:

$$
n=1
$$

Therefore:

$$
X\in\mathbb{R}^{6\times1}
$$

Each row represents one sample.

Each column represents one feature.

In [3]:
print("Number of samples:", X.shape[0])
print("Number of features:", X.shape[1])

Number of samples: 6
Number of features: 1


## 4. Creating the Model

We will use **Linear Regression** as a simple example.

A linear regression model can be represented as:

$$
\hat{y}=wx+b
$$

where:

- $x$ is the input feature.
- $w$ is the model coefficient.
- $b$ is the intercept.
- $\hat{y}$ is the predicted value.

During training, the model learns suitable values of $w$ and $b$ from the training data.

Creating the model object does not mean that the model has already learned from the dataset.

The model must still be trained using the training data.

In [4]:
model = LinearRegression()

print(model)

LinearRegression()


## 5. Training the Model

In scikit-learn, model training is commonly performed using the `fit()` method.

The basic operation is:

`model.fit(X_train, y_train)`

The `fit()` operation provides the model with the training features and their corresponding target values.

Conceptually:

$$
(X_{\text{train}},y_{\text{train}})
\rightarrow
\texttt{fit()}
\rightarrow
\text{Trained Model}
$$

For Linear Regression, the training process determines suitable values for the model parameters.

After training, the model can be used to make predictions.

In [5]:
model.fit(X, y)

print("Model training completed.")

Model training completed.


## 6. Learned Model Parameters

After training, the model has learned parameters.

For Linear Regression:

$$
\hat{y}=wx+b
$$

The learned coefficient is $w$.

The learned intercept is $b$.

In scikit-learn, these values can be accessed using:

- `model.coef_`
- `model.intercept_`

These values were learned from the training data.

In [6]:
print("Coefficient:", model.coef_[0])
print("Intercept:", model.intercept_)

Coefficient: 7.485714285714285
Intercept: 27.46666666666667


## 7. What Is Inference?

**Inference** is the process of using a trained Machine Learning model to generate predictions for input data.

The model has already learned its parameters during training.

During inference, we provide new input data.

Conceptually:

$$
x_{\text{new}}
\rightarrow
\text{Trained Model}
\rightarrow
\hat{y}_{\text{new}}
$$

For our Linear Regression model:

$$
\hat{y}=wx+b
$$

The learned values of $w$ and $b$ are used to calculate the prediction.

Inference does not mean that the model is learning again.

The trained model is being applied to new input data.

## 8. Making a Prediction

In scikit-learn, predictions are commonly generated using the `predict()` method.

The basic operation is:

`model.predict(X_new)`

The `predict()` method receives input features and returns the model's predictions.

The basic process is:

$$
\text{New Features}
\rightarrow
\texttt{predict()}
\rightarrow
\text{Predicted Target}
$$

In [7]:
X_new = np.array([
    [7]
])

prediction = model.predict(X_new)

print("Predicted score:", prediction[0])

Predicted score: 79.86666666666666


## 9. Training vs Inference

Training and inference are different operations.

### Training

During training:

$$
X_{\text{train}},y_{\text{train}}
\rightarrow
\text{Learning}
\rightarrow
\text{Model Parameters}
$$

The model learns from data.

### Inference

During inference:

$$
X_{\text{new}}
\rightarrow
\text{Trained Model}
\rightarrow
\hat{y}
$$

The model uses its learned parameters to produce predictions.

The fundamental distinction is:

> **Training learns the model. Inference applies the trained model.**

## 10. Making Predictions for Multiple Samples

Inference is not limited to a single sample.

Suppose we want predictions for students who studied:

$$
7,\;8,\;9
$$

hours.

The input must maintain the same feature structure used during training.

Since our model has one feature:

$$
X_{\text{new}}\in\mathbb{R}^{3\times1}
$$

Each row represents one new sample.

In [8]:
X_new = np.array([
    [7],
    [8],
    [9]
])

predictions = model.predict(X_new)

print("Predictions:")
print(predictions)

Predictions:
[79.86666667 87.35238095 94.83809524]


## 11. Prediction for Multiple Samples

The model returns one prediction for each input sample.

If:

$$
X_{\text{new}}
=
\begin{bmatrix}
7\\
8\\
9
\end{bmatrix}
$$

then:

$$
\hat{y}
=
\begin{bmatrix}
\hat{y}_1\\
\hat{y}_2\\
\hat{y}_3
\end{bmatrix}
$$

Therefore:

$$
\text{Number of Predictions}
=
\text{Number of Input Samples}
$$

The trained model applies the learned function independently to each input sample.

In [9]:
results = pd.DataFrame({
    "Study Hours": X_new.flatten(),
    "Predicted Score": predictions
})

results

,Study Hours,Predicted Score
0,7,79.866667
1,8,87.352381
2,9,94.838095


## 12. Training Data vs New Data

It is important to distinguish between training data and new data.

### Training Data

Training data is used to learn the model.

$$
X_{\text{train}},y_{\text{train}}
$$

### New Data

New data was not used to train the model.

$$
X_{\text{new}}
$$

During inference:

$$
X_{\text{new}}
\rightarrow
f_{\theta}
\rightarrow
\hat{y}
$$

where $f_{\theta}$ represents the trained model.

A major purpose of Machine Learning is to learn models that can make useful predictions for new data.

## 13. The Trained Model as a Function

After training, we can think of the model as a function:

$$
f_{\theta}:X\rightarrow Y
$$

For our Linear Regression example:

$$
f_{\theta}(x)=wx+b
$$

Training determines the model parameters:

$$
\theta=(w,b)
$$

Inference applies the learned function:

$$
\hat{y}=f_{\theta}(x)
$$

Therefore:

$$
\boxed{
\text{Training learns the parameters}
}
$$

and:

$$
\boxed{
\text{Inference applies the learned function}
}
$$

## 14. Prediction and Evaluation Are Different

Making predictions and evaluating predictions are different operations.

### Prediction

The model produces:

$$
\hat{y}
$$

from input:

$$
x
$$

### Evaluation

If the actual target $y$ is available, we can compare:

$$
y
\quad\text{and}\quad
\hat{y}
$$

using an evaluation metric.

For example, Mean Squared Error is:

$$
MSE
=
\frac{1}{m}
\sum_{i=1}^{m}
(y_i-\hat{y}_i)^2
$$

Therefore:

$$
\text{Input}
\rightarrow
\text{Prediction}
\rightarrow
\text{Evaluation}
$$

Prediction is about producing an output.

Evaluation is about measuring how good that output is.

Model evaluation will be studied in greater detail in a later notebook.

## 15. Training on the Training Set

In a proper Machine Learning workflow, the model is trained using the training set.

The basic process is:

$$
(X_{\text{train}},y_{\text{train}})
\rightarrow
\text{Model Training}
$$

The model should not be trained using the test set.

The test set is reserved for evaluating the final model.

The complete principle is:

$$
\boxed{
\text{Train on Training Data}
}
$$

$$
\boxed{
\text{Select Using Validation Data}
}
$$

$$
\boxed{
\text{Evaluate Using Test Data}
}
$$

## 16. A Complete Basic Training and Inference Workflow

A basic Machine Learning workflow can be represented as:

$$
\text{Dataset}
$$

$$
\downarrow
$$

$$
\text{Training / Validation / Test Split}
$$

$$
\downarrow
$$

$$
\text{Training Data}
\rightarrow
\text{Model Training}
$$

$$
\downarrow
$$

$$
\text{Trained Model}
$$

$$
\downarrow
$$

$$
\text{New Input}
\rightarrow
\text{Inference}
\rightarrow
\text{Prediction}
$$

If actual targets are available:

$$
\text{Prediction}
+
\text{Actual Target}
\rightarrow
\text{Evaluation}
$$

This represents the basic practical flow of a Machine Learning system.

## 17. Model Training in Practice

Model training is normally performed during the development stage.

The general process is:

$$
\text{Training Data}
\rightarrow
\text{Learning Algorithm}
\rightarrow
\text{Trained Model}
$$

The trained model can then be stored and used later.

A trained model may eventually be integrated into:

- A Python application
- A backend service
- An API
- A data-processing pipeline
- A production Machine Learning system

The important principle remains:

> The model is trained first and then used for inference.

## 18. Inference in Practice

After a model has been trained, inference can happen repeatedly.

For example:

$$
x_1
\rightarrow
\text{Model}
\rightarrow
\hat{y}_1
$$

$$
x_2
\rightarrow
\text{Model}
\rightarrow
\hat{y}_2
$$

$$
x_3
\rightarrow
\text{Model}
\rightarrow
\hat{y}_3
$$

A deployed Machine Learning system may receive many new inputs and generate predictions continuously.

The model does not need to be retrained every time a prediction is requested.

Training and inference are separate stages.

## 19. Model Parameters and Hyperparameters

During training, a model learns **parameters** from the training data.

For example, in:

$$
\hat{y}=wx+b
$$

the values:

$$
w,\;b
$$

are learned parameters.

A **hyperparameter** is a configuration value chosen as part of the model-development process.

Examples include:

- Learning rate
- Number of neighbors
- Maximum tree depth
- Number of trees
- Regularization strength

The validation set can be used to compare different hyperparameter configurations.

Therefore:

$$
\text{Training}
\rightarrow
\text{Learn Parameters}
$$

while:

$$
\text{Model Development}
\rightarrow
\text{Select Hyperparameters}
$$

## 20. Training and Inference — Key Difference

| Aspect | Training | Inference |
|---|---|---|
| Purpose | Learn the model | Generate predictions |
| Input | Training data | New input data |
| Target | Used during supervised training | Usually unavailable during real-world prediction |
| Model parameters | Learned | Used |
| Main operation | Learning/optimization | Prediction |
| Frequency | Usually during model development | Can occur repeatedly after deployment |

The fundamental distinction is:

$$
\boxed{
\text{Training = Learning}
}
$$

$$
\boxed{
\text{Inference = Applying}
}
$$

## 21. Final Summary

Model training is the process of learning a Machine Learning model from training data.

For supervised learning:

$$
(X_{\text{train}},y_{\text{train}})
\rightarrow
\text{Training}
\rightarrow
\text{Trained Model}
$$

Inference is the process of using the trained model to generate predictions:

$$
X_{\text{new}}
\rightarrow
\text{Trained Model}
\rightarrow
\hat{y}
$$

In scikit-learn, the basic operations are `model.fit(X_train, y_train)` for training and `model.predict(X_new)` for inference.

The complete basic idea is:

$$
\boxed{
\text{Data}
\rightarrow
\text{Train}
\rightarrow
\text{Trained Model}
\rightarrow
\text{New Data}
\rightarrow
\text{Inference}
\rightarrow
\text{Prediction}
}
$$

This establishes the practical foundation for the Machine Learning workflow that will be developed in the following notebooks.